// import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// // This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// export default sidebars;

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/introduction',
        'getting-started/installation',
        'getting-started/usage',
        'getting-started/tailwind-integration',
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Components',
    //   items: [
    //     'components/layout',
    //     'components/ui-elements',
    //     'components/form-elements',
    //     'components/table',
    //     'components/advanced-ui',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Utilities',
    //   items: [
    //     'utilities/cn-utility',
    //     'utilities/theme-support',
    //     'utilities/responsive',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Guides',
    //   items: [
    //     'guides/add-component',
    //     'guides/theming',
    //     'guides/custom-table-column',
    //     'guides/reusable-forms',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Examples',
    //   items: [
    //     'examples/dashboard-layout',
    //     'examples/table-with-features',
    //     'examples/modal-form',
    //     'examples/custom-switch',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'API Reference',
    //   items: [
    //     'api/button-props',
    //     'api/table-props',
    //     'api/types-and-interfaces',
    //     'api/hooks',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Contributing',
    //   items: [
    //     'contributing/how-to-contribute',
    //     'contributing/code-structure',
    //     'contributing/dev-guide',
    //   ],
    // },
    // 'changelog',
    // 'license',
  ],
};

module.exports = sidebars;